### ISSUE TITLE
$ref in fields replaces all attributes, instead of merge

### ISSUE THREAD

**Issue by jasonh-n-austin** [BigstickCarpet/swagger-parser#14]
## Scenario 1:
In this example, we use `x-nullable` as a vendor extension to represent when a field is allowed to have an expressly `null` value. As it stands now, we have to make `address.yaml` contain this property for all uses (which is bad, because it's not always nullable).
``` yml
# item.yaml
shipping_address:
  x-nullable: true  # I will be killed by the following $ref
  $ref: "address.yaml"
```
``` yml
# address.yaml
  description: A generic address
  properties:
    # fields here
```
Once this is deferenced, `x-nullable` has disappeared. It seems like this should be a merge, to allow for overrides as well. 
``` yml
# item.yaml
shipping_address:
  description: A generic address
  properties:
    # fields here
```

## Scenario 2:
When using generic/common objects, it's nice to provide usage-specific descriptions. Today we have to use one description for all uses, as the description will be stripped by dereferencing.

``` yml
# item.yaml
shipping_address:
  description: Shipping address for the item  # I will disappear after $ref resolves
  $ref: "address.yaml"
```

After dereferencing, this will strip off the overriden description:
``` yml
# item.yaml
shipping_address:
  description: A generic address
  properties:
    # fields here
```
