### ISSUE TITLE
Verify discriminator property

### ISSUE THREAD

**Issue by mgold** [BigstickCarpet/swagger-parser#49]
Schema objects are allowed to have a [discriminator property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13), which is described as

>The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. **The property name used MUST be defined at this schema and it MUST be in the `required` property list.** When used, the value MUST be the name of this schema or any schema that inherits it.

The bolded sentence seems like something this parser should check. That is, these should fail (assume valid rest of swagger file):

```yaml
# petType is not required
definitions:
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
```

```yaml
# petType is not in properties
definitions:
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
    required:
    - name
```
