### ISSUE TITLE
Order of resolution of references - resolve remotes first?

### ISSUE THREAD

**Issue by mrchief** [BigstickCarpet/swagger-parser#50]
Given this folder structure:

```
|   index.yaml
|   parameters.yaml
|   responses.yaml
|   
+---definitions
|   |   index.yaml
|   |   
|   +---error
|   |       error_model.yaml
|   |       extended_error_model.yaml
|               
\---paths
    |   index.yaml
```
Consider this yaml:

**index.yaml**

```yaml
swagger: '2.0'

info:
  version: 1.0.0
  title: User API
  description: User specific API

schemes:
  - http
  - https

produces:
  - application/json
  - text/json

paths:
  $ref: ./paths/index.yaml

definitions:
  $ref: ./definitions/index.yaml

parameters:
  $ref: ./parameters.yaml

responses:
  $ref: ./responses.yaml
```

**responses.yaml**
```yaml
# Common responses
200:
  description: OK
  schema:
    type: string

DefaultError:
  description: Error payload
  schema:
    $ref: '#/definitions/ExtendedErrorModel'
```

**extended_error_model.yaml**
```yaml
allOf:
- $ref: '#/definitions/ErrorModel'
- type: object
  properties:
    detail:
      type: string
    meta:
      type: string
```

**error_model.yaml**
```yaml
type: object
required:
  - status
  - code
  - title
properties:
  code:
    type: integer
  title:
    type: string
  status:
    type: integer
    minimum: 100
    maximum: 600
```

`SwaggerParser.validate('index.yaml')` fails because `'#/definitions/ExtendedErrorModel'` doesn't exist inside **responses.yaml**. However, if I use [json-refs](https://github.com/whitlockjc/json-refs) and [js-yaml](https://github.com/nodeca/js-yaml) to load and parse the YAML, the resolution works.

I believe this is because json-refs first resolves all remote refs, then proceeds with local ones.

I'm not sure if the spec (OAI or json ref) dictates one way or the other. So I'm not sure if this is an issue or not. 

Could you please shed some light on this?

**Comment by BigstickCarpet** [comment]
Hi.  Sorry for not replying sooner.  I've been away on holiday.

The `$ref` in `responses.yaml` is invalid, because it's pointing to a definition _within the same file_, which doesn't exist (see the [JSON Reference spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) for details).

Instead of referencing a type definition, you need to directly reference the `extended_error_model.yaml` file instead, like this:

```yaml
# Common responses
200:
  description: OK
  schema:
    type: string

DefaultError:
  description: Error payload
  schema:
    $ref: 'definitions/error/extended_error_model.yaml'     # <-- referencing the file
```

**Comment by BigstickCarpet** [comment]
Another way to fix the problem would be to point to the type definition in your `index.yaml` or `definitions/index.yaml` file, like this:

```yaml
# Common responses
200:
  description: OK
  schema:
    type: string

DefaultError:
  description: Error payload
  schema:
    $ref: 'index.yaml#/definitions/ExtendedErrorModel'     # <-- referencing the type definition
```
